version: '3'
services:
  app:
    build:
      context: .
      args:
        NODE_ENV: development
    entrypoint: yarn develop
    ports:
      - 1337:1337
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    depends_on:
      - postgres
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: strapi
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
    restart: always

  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  node_modules:
  postgres_data:
